### ISSUE TITLE
[Question] Doesn't work for "metapackages"

### ISSUE THREAD

**Issue by lonix1** [spectresystems/snitch#11]
First of all, thanks for making this really great tool!

Let's say I have this:

````xml
<PackageReference Include="Serilog.AspNetCore" Version="3.4.0" />
<PackageReference Include="Serilog.Extensions.Hosting" Version="3.1.0" />
````

[Serilog.AspNetCore 3.4.0](https://www.nuget.org/packages/Serilog.AspNetCore/3.4.0) depends on [Serilog.Extensions.Hosting 3.1.0](https://www.nuget.org/packages/Serilog.Extensions.Hosting/3.1.0). So I assumed this tool would tell to remove the latter as it's already referenced.

However it doesn't, and I get `Everything looks good!`

Am I misusing or misunderstanding this tool?

**Comment by patriksvensson** [comment]
@lonix1 Thanks!

Snitch will only detect transient packages between projects, and not between packages. Not impossible to add but nothing that is currently supported.

**Comment by lonix1** [comment]
Ohhh! Now I get it. So if a redudant package is added to a referenced project, that would be detected.

---

Can I add the above use case (which is very common) as a new feature request issue? I don't want to spam your issues list. :smile:

**Comment by patriksvensson** [comment]
@lonix1 Feel free to add an issue. Much appreciated that you bring this up!
