### ISSUE TITLE
Add support of fsproj

### ISSUE THREAD

**Issue by nojaf** [spectresystems/snitch#13]
Hello,

Would it be add support for `fsproj` files as well?
![image](https://user-images.githubusercontent.com/2621499/109812540-7a77aa00-7c2c-11eb-8133-4f3be3134e4a.png)
Or is this a known limitation?

**Comment by patriksvensson** [comment]
@nojaf It should work with fsproj and vbproj without problem, but I think there is some hardcoded stuff that checks for csproj extensions and similar, and that's probably what you're experiencing.

A PR would be very welcome for this!

**Comment by nojaf** [comment]
It seems like there is indeed a hardcoded check for csproj right now:
https://github.com/spectresystems/snitch/blob/2ed45c6dfdd1d740b18b95a2c205d4b805d65dc0/src/Snitch/Analysis/Utilities/PathUtility.cs#L46

I'll submit a PR in the following days.
