### ISSUE TITLE
Snitching on pre-release nuget package references

### ISSUE THREAD

**Issue by kerwinc** [spectresystems/snitch#30]
Hey,

I'm looking at preventing pre-release nuget package references from making it into main/master during merge/pull request build. I do understand that devs sometimes need to reference pre-release builds while building or validating a feature but I want to catch them before they make it into the main branch.

I have been considering a simple PowerShell script or custom tool to call during a merge build which is fine, but it might be sexier if this was part of Snitch.

It could be slightly out of Snitch's responsibilities but it does align with the general intent and tool name ;).

Do you think this is something we could add to Snitch?

Option 1:
- Return > 0 exit code when there are pre-release nuget references and "--strict" is passed.

Option 2:
- Include a new flag to either opt-in or opt-out from validating package references e.g. `--validate-package-versions  or --no-prereleases-versions`.
- Return > 0 exit code when there are pre-release nuget references and "--strict" is passed.

I don't mind submitting a PR if you guys are happy to add this feature.

**Comment by patriksvensson** [comment]
@kerwinc Sounds like a reasonable request. We should go with option two and let users opt-in to this functionality with a `-no-prerelease` flag and return exit code > 0 when `--strict` is passed.

A PR would be appreciated since I currently do not have time to do it.

**Comment by kerwinc** [comment]
Awesome. I'll get cracking on it.

**Comment by kerwinc** [comment]
Hey @patriksvensson. PR is ready. Shout if missed anything.

**Comment by kerwinc** [comment]
Hey @patriksvensson, have you managed to have a look at this PR yet?

**Comment by patriksvensson** [comment]
Yeah, sorry for the delay. It’s been merged so closing this issue. Thanks!

**Comment by kerwinc** [comment]
Thanks. No worries.

Can you please push a new version to the NuGet feed. I did update the readme so the latest published version doesn't line up with the documented args.
