### ISSUE TITLE
Order by project then alpha

### ISSUE THREAD

**Issue by Poltuu** [spectresystems/snitch#4]
Great project. Just wanted to say that ordering by projects first would be more practical when you have a lot of projects.

**Comment by patriksvensson** [comment]
@Poltuu Can you elaborate what you mean by "ordering by projects first"?

**Comment by Poltuu** [comment]
sorry, I misunderstood what this tool does. I expected the tool to *recursively* find redundant packages, in which case the console should output detail for each project separately instead of, well, in one list. But this not what this does, so nevermind :)
